name: pipeline
env: 
  ARTIFACT_NAME: hello-python
on: [push]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      
    - name: Run the script
      run: python hello.py

  build: 
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create an artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
    
      
      
